# Generated by Django 4.1 on 2022-09-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatterbox', '0003_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
