# Generated by Django 4.1 on 2022-09-21 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mychatterbox', '0004_chatmessage_received_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='received_at',
            field=models.DateTimeField(null=True),
        ),
    ]
